import type { Metadata } from "next";
import { Roboto, Inter } from 'next/font/google';
import NavBar from "@/components/navbar";
import SideBar from "@/components/sidebar";
import "./../globals.css";


const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto', // Creates a CSS variable
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${roboto.variable} antialiased`}
      >
        <div className="flex h-screen bg-white font-sans text-slate-800 overflow-hidden">

          {/* 1. The Constant Sidebar on the left */}
          <SideBar />

          {/* The right side container for Navbar + Dynamic Content */}
          <div className="flex-1 flex flex-col overflow-hidden bg-gray-50">

            {/* 2. The Constant Navbar at the top */}
            <NavBar />

            {/* 3. The Dynamic Content Area */}
            {/* overflow-auto ensures only this section scrolls, not the whole page */}
            <main className="flex-1 overflow-auto p-8">
              {children}
            </main>

          </div>

        </div>
      </body>
    </html>
  );
}