import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/navbar";
import SideBar from "@/components/sidebar";
import "./../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen bg-white font-sans text-slate-800 overflow-hidden">

          {/* 1. The Constant Sidebar on the left */}
          <SideBar />

          {/* The right side container for Navbar + Dynamic Content */}
          <div className="flex-1 flex flex-col overflow-hidden bg-gray-50">

            {/* 2. The Constant Navbar at the top */}
            <NavBar />

            {/* 3. The Dynamic Content Area */}
            {/* overflow-auto ensures only this section scrolls, not the whole page */}
            <main className="flex-1 overflow-auto p-8">
              {children}
            </main>

          </div>

        </div>
      </body>
    </html>
  );
}
